apiVersion: apps/v1
kind: Deployment
metadata:
  name: group
spec:
  selector:
    matchLabels:
      app: group
  template:
    metadata:
      labels:
        app: group
    spec:
      containers:
      - name: group
        image: pongpong41/noomnim-chat-group
        ports:
        - containerPort: 3010
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PASSWORD
          value: password
